import { notFound } from "next/navigation";
/* eslint-disable @next/next/no-img-element -- Brand Kit assets use their original local paths */
import { AppHeader } from "@/components/layout/AppHeader";
import { BrandTemplatePreviews } from "@/components/brand/BrandTemplatePreviews";
import { getBrand } from "@/brands";
import { getTemplatesForBrand } from "@/templates/registry";

export default async function BrandDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const brand = getBrand((await params).slug); if (!brand) notFound();
  const templates = getTemplatesForBrand(brand.id);
  return <div className="flex h-full flex-col bg-[#151815] text-white"><AppHeader/><main className="mx-auto w-full max-w-6xl flex-1 overflow-y-auto px-6 py-10"><p className="app-kicker">Brand Kit</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-semibold tracking-[-.04em]">{brand.name}</h1><p className="mt-2 text-sm text-white/45">{brand.description}</p></div><span className="rounded-full border border-amber-300/20 bg-amber-300/10 px-3 py-1 text-xs text-amber-200">{brand.logos.primary.placeholder ? "Assets demonstrativos" : "Assets oficiais"}</span></div><section className="mt-10 grid gap-6 lg:grid-cols-2"><div className="app-panel"><h2 className="editor-section-title">Logos</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(brand.logos).map(([variant, logo]) => <div key={variant} className="rounded-lg bg-[#f1efe9] p-4"><img src={logo.path} alt={logo.name} className="h-16 w-full object-contain"/><p className="mt-2 text-center text-[10px] uppercase tracking-wider text-black/50">{variant} · {logo.placeholder ? "placeholder" : "oficial"}</p></div>)}</div></div><div className="app-panel"><h2 className="editor-section-title">Cores e tipografia</h2><div className="mt-4 grid grid-cols-3 gap-3">{Object.entries(brand.colors).filter((entry): entry is [string, string] => typeof entry[1] === "string").map(([name, color]) => <div key={name}><div className="h-16 rounded-lg border border-white/10" style={{ background: color }}/><p className="mt-2 text-[10px] text-white/45">{name}<br/>{color}</p></div>)}</div><div className="mt-6 space-y-2 text-sm"><p style={{ fontFamily: brand.typography.headline.family }} className="text-2xl">Headline · {brand.typography.headline.family}</p><p style={{ fontFamily: brand.typography.body.family }} className="text-white/60">Body · {brand.typography.body.family}</p></div></div></section><section className="mt-10"><div className="mb-4 flex items-end justify-between"><div><p className="editor-section-title">Templates</p><h2 className="mt-1 text-2xl font-semibold">{templates.length} sistemas demonstrativos</h2></div><span className="text-xs text-white/35">Feed + Stories</span></div><BrandTemplatePreviews brand={brand} templates={templates}/></section></main></div>;
}
